services:
  db:
    image: mariadb:10.6
    container_name: frappe-db
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-frappe}
      MYSQL_USER: ${MYSQL_USER:-frappe}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-frappe}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - frappe-net

  redis-cache:
    image: redis:7-alpine
    container_name: frappe-redis-cache
    restart: on-failure
    networks:
      - frappe-net

  redis-queue:
    image: redis:7-alpine
    container_name: frappe-redis-queue
    restart: on-failure
    networks:
      - frappe-net

  frappe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frappe-app
    restart: on-failure
    depends_on:
      - db
      - redis-cache
      - redis-queue
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - frappe-net
    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
      - logs-data:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  sites-data:
  logs-data:

networks:
  frappe-net:
    name: frappe-net
