version: '3.8'

services:
  # Database
  db:
    image: mariadb:10.6
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: frappe123
      MYSQL_DATABASE: frappe
      MYSQL_USER: frappe
      MYSQL_PASSWORD: frappe123
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost --password=frappe123
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # Redis Cache
  redis-cache:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_cache_data:/data

  # Redis Queue  
  redis-queue:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_queue_data:/data

  # Configurator (runs once to setup config)
  configurator:
    image: frappe/erpnext:v15.27.0
    restart: "no"
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y netcat-openbsd;
        while ! nc -z db 3306; do echo "Waiting for database..."; sleep 2; done;
        while ! nc -z redis-cache 6379; do echo "Waiting for redis-cache..."; sleep 2; done;
        while ! nc -z redis-queue 6379; do echo "Waiting for redis-queue..."; sleep 2; done;
        echo "All services ready, configuring...";
        cd /home/frappe/frappe-bench;
        bench set-config -g db_host db;
        bench set-config -g redis_cache redis://redis-cache:6379;
        bench set-config -g redis_queue redis://redis-queue:6379;
        bench set-config -g redis_socketio redis://redis-cache:6379;
        bench set-config -g socketio_port 3000;
        echo "Configuration completed!";
    environment:
      DB_HOST: db
      DB_PORT: 3306
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
      REDIS_SOCKETIO: redis://redis-cache:6379
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      db:
        condition: service_healthy

  # Site Creator (runs once to create ERPNext site)
  create-site:
    image: frappe/erpnext:v15.27.0
    restart: "no"
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y netcat-openbsd;
        while ! nc -z db 3306; do echo "Waiting for database..."; sleep 2; done;
        while ! nc -z redis-cache 6379; do echo "Waiting for redis-cache..."; sleep 2; done;
        while ! nc -z redis-queue 6379; do echo "Waiting for redis-queue..."; sleep 2; done;
        cd /home/frappe/frappe-bench;
        if [[ ! -d "sites/100.100.0.100.traefik.me" ]]; then
          echo "Creating new ERPNext site: 100.100.0.100.traefik.me";
          bench new-site 100.100.0.100.traefik.me --no-mariadb-socket --mariadb-root-password frappe123 --install-app erpnext --admin-password 'tFcBHAEnYyu2Fy2j';
          bench --site 100.100.0.100.traefik.me set-config db_host db;
          bench --site 100.100.0.100.traefik.me set-config redis_cache 'redis://redis-cache:6379';
          bench --site 100.100.0.100.traefik.me set-config redis_queue 'redis://redis-queue:6379';
          bench --site 100.100.0.100.traefik.me set-config redis_socketio 'redis://redis-cache:6379';
        else
          echo "Site 100.100.0.100.traefik.me already exists, skipping creation";
        fi;
        echo "Site setup completed successfully!";
    environment:
      SITE_NAME: 100.100.0.100.traefik.me
      ADMIN_PASSWORD: tFcBHAEnYyu2Fy2j
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - configurator

  # Backend (Gunicorn)
  backend:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    command: ["start"]
    environment:
      SOCKETIO_PORT: 3000
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - create-site

  # Frontend (Nginx)
  frontend:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    entrypoint: ["/usr/local/bin/nginx-entrypoint.sh"]
    command: []
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:3000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      FRAPPE_SITE_NAME_HEADER: 100.100.0.100.traefik.me
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - websocket

  # WebSocket (Socket.IO)
  websocket:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    command: ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-queue

  # Scheduler
  scheduler:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    command: ["schedule"]
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - create-site

  # Queue Workers
  queue-short:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    command: ["worker"]
    environment:
      WORKER_TYPE: short
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - create-site

  queue-long:
    image: frappe/erpnext:v15.27.0
    restart: unless-stopped
    command: ["worker"]
    environment:
      WORKER_TYPE: long
    volumes:
      - sites_data:/home/frappe/frappe-bench/sites
    depends_on:
      - create-site

volumes:
  sites_data:
  db_data:
  redis_cache_data:
  redis_queue_data:







