# fly.toml app configuration file generated for erpnext-fly-app on 2025-08-13T16:16:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'erpnext-fiberelements-app'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  DB_HOST = 'your-fly-db-host.internal'
  DB_PORT = '5432'
  FRAPPE_SITE_NAME_HEADER = 'your-app-name.fly.dev'

  SOCKETIO = 'http://localhost:9000'

[processes]
  app = 'bench start'
  queue-long = 'bench worker --queue long'
  queue-short = 'bench worker --queue short'
  scheduler = 'bench schedule'
  websocket = 'node /home/frappe/frappe-bench/apps/frappe/socketio.js'

[[mounts]]
  source = 'sites_volume'
  destination = '/home/frappe/frappe-bench/sites'
  processes = ['app', 'queue-short', 'queue-long', 'scheduler']



[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
