[build]
builder = "dockerfile"

[deploy]
startCommand = "bench start"
healthcheckPath = "/api/method/ping"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[[services]]
name = "mariadb"
plugin = "mariadb"

[[services]]
name = "redis"
plugin = "redis"
