[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = [
    "Dockerfile",
    "docker-entrypoint-railway.sh", 
    "supervisord.conf",
    "railway.toml"
]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
volumes = [
  { mountPoint = "/home/frappe/persistent" }
]
