redis_cache: redis-server --port 13000
redis_queue: redis-server --port 13001
redis_socketio: redis-server --port 13002

web: gunicorn --bind 0.0.0.0:8000 --threads 2 --workers 2 --timeout 120 --worker-class gthread frappe.app:application --preload

socketio: node /home/frappe/frappe-bench/apps/frappe/socketio.js

worker_short: bench worker --queue short
worker_long: bench worker --queue long
worker_default: bench worker --queue default

schedule: bench schedule
