# Use the official ERPNext image as the base
ARG FRAPPE_VERSION=v15.30.0
FROM frappe/erpnext:${FRAPPE_VERSION}

# Set the user to frappe to ensure correct permissions
USER frappe

# Argument to receive the Base64 encoded apps.json. The base image's entrypoint
# will handle the installation of apps listed in this JSON.
ARG APPS_JSON_BASE64
